{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "keycloak-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak-cluster.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- if .Values.httpRoute.hostnames }}
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
    {{- else }}
    - {{ .Values.hostname.hostname }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "keycloak-cluster.fullname" . }}-service
          port: 8080
{{- end }}
